name: CareerCradle
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2020.12.5=ha878542_0
  - certifi=2020.12.5=py39hf3d152e_1
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgomp=9.3.0=h2828fa1_18
  - libstdcxx-ng=9.3.0=h6de172a_18
  - ncurses=6.2=h58526e2_4
  - openssl=1.1.1k=h7f98852_0
  - pip=21.0.1=pyhd8ed1ab_0
  - python=3.9.2=hffdb5ce_0_cpython
  - python_abi=3.9=1_cp39
  - readline=8.0=he28a2e2_2
  - setuptools=49.6.0=py39hf3d152e_3
  - sqlite=3.35.3=h74cdb3f_0
  - tk=8.6.10=h21135ba_1
  - tzdata=2021a=he74cb21_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
  - pip:
    - asgiref==3.3.1
    - beautifulsoup4==4.9.3
    - cachetools==4.2.1
    - chardet==4.0.0
    - click==7.1.2
    - django==3.1.7
    - django-environ==0.4.5
    - flask==1.1.2
    - google-api-core==1.26.3
    - google-api-python-client==2.0.2
    - google-auth==1.28.0
    - google-auth-httplib2==0.1.0
    - googleapis-common-protos==1.53.0
    - greenlet==1.0.0
    - httplib2==0.19.0
    - idna==2.10
    - itsdangerous==1.1.0
    - jinja2==2.11.3
    - jsonpickle==2.0.0
    - markupsafe==1.1.1
    - oauth2client==4.1.3
    - packaging==20.9
    - protobuf==3.15.6
    - psycopg2==2.8.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pymongo==3.11.3
    - pyparsing==2.4.7
    - pytz==2021.1
    - requests==2.25.1
    - rsa==4.7.2
    - six==1.15.0
    - soupsieve==2.2.1
    - sqlalchemy==1.4.3
    - sqlparse==0.4.1
    - uritemplate==3.0.1
    - urllib3==1.26.4
    - werkzeug==1.0.1
prefix: /home/priyam145/miniconda3/envs/CareerCradle
